services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:15.4
    restart: always
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aleum
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # networks:
    #   - elastic
